### ISSUE TITLE
Open States Districts Not Working

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/coop.palantetech.electoral#3]
**We've been using this extension for a year and I'm still using the custom fields from the original version.** Using CiviCRM 4.7.20 with current version of WordPress. 
Did a git clone https://github.com/josephlacey/coop.palantetech.electoral
**Ran this job:**
Open States API - Districts (Daily) Adds state representative districts to contactsAPI Entity: openStatesAPI Action: districts | limit=100
**Flashed this up on the screen briefly:**
Warning: Illegal string offset 'district' in /myDomain.org/wp-content/civicrm/extensions/coop.palantetech.electoral/api/v3/OpenStates.php on line 305
Warning: Illegal string offset 'chamber' in /myDomain.org/wp-content/civicrm/extensions/coop.palantetech.electoral/api/v3/OpenStates.php on line 306
**The Job Log Shows:**
Finished execution of Open States API - Districts with result: Failure, Error message: 'h' is not a valid option for field custom_4

**Comment by jimcrist** [comment]
Our all volunteer organization doesn't have much money, but I just got approval to become CiviCRM member. Does that help get any attention here? Would really like to get this working... Thanks...

**Comment by josephlacey** [comment]
Hi Jim,

This could be a few issues.  You might be requesting data against an unregistered or unactivated API key.  If you're using your old key, you'll need to get a new one.  If you registered for a new one but didn't activate it, you'll need to validate the email address associated with it. The registration process is a double opt-in (kind of like signing up for a public mailing list).

To test that your API key is registered and activated, you can run a manual look up of a known good address following this URL structure.  (You should be able to pull a latitude and longitude from an address in Civi.)

https://openstates.org/api/v1/legislators/geo/?apikey=XXXXXXXXXX&lat=XXXXXXXXXX&long=XXXXXXXXXX

If the manual look up returns valid, then it could be a bad address in your dataset.  To verify we'll need to see the information we're getting back from OpenStates.  Can you add this line to the api/v3/OpenStates.php file just above the foreach where it parses the individual districts?  That should be [line 303](https://github.com/josephlacey/coop.palantetech.electoral/blob/master/api/v3/OpenStates.php#L303) of the latest code base, so just above that.

` CRM_Core_Error::debug_var("districts", $districts);`

This will output the returned data for each look up to the CiviCRM log file, so set the limit in the scheduled job to something small like 2 or 3.  Then copy the failing output here.

Thanks,
Joseph

**Comment by jimcrist** [comment]
It's working!  It was a comedy of errors on my part...sorry!

**Comment by josephlacey** [comment]
Hey Jim,

I'm glad it's working for you.

Joseph
